### PR TITLE
feat: add ghostty theme config

### PR DESCRIPTION
**Pull request by JuxhinDB**
Adds theme config for newly released ghostty terminal

image

### CODE REVIEW

**Review by xero — APPROVED** [review]
👁️👁️👍
thanx!

**Comment by JuxhinDB** [comment]
Welcome @xero -- I believe you need to merge as I don't have write access

**Comment by xero** [comment]
i reviewed it on my phone. i wanna test it on my computer this afternoon. been meaning to test drive ghostty

**Comment by xero** [comment]
looks great! thanx again

**Pull request merged**
